### ISSUE TITLE
clj.native-image keeps generating a fallback image

### ISSUE THREAD

**Issue by wbehrens-on-gh** [taylorwood/clj.native-image#25]
I'm not sure if this is a graal issue or a clj.native-image issue but when attempting to create a native image I keep getting a failure and it generates a fallback image

`deps.edn` snippet:
```
:aliases {:native-image {:main-opts ["-m" "clj.native-image" "server.main"
                                      "--report-unsupported-elements-at-runtime"
                                      "--initialize-at-build-time"
                                      "-Dclojure.compiler.direct-linking=true"
                                      "-H:Name=behr_codes"]
                         :extra-deps {clj.native-image/clj.native-image
                                      {:git/url "https://github.com/taylorwood/clj.native-image.git"
                                       :sha "7708e7fd4572459c81f6a6b8e44c96f41cdd92d4"}}}}
```

`clj -M:native-image` output:
[out.log](https://github.com/taylorwood/clj.native-image/files/8679528/out.log)

**Comment by taylorwood** [comment]
Sorry, can't diagnose this without a reproducible example with source. You may want to check the Graal channel on Clojurians Slack for help.
