### ISSUE TITLE
Image name mixup

### ISSUE THREAD

**Issue by stathissideris** [taylorwood/clj.native-image#4]
If I use the alias below to make a native image that includes support for js, I somehow end up with an executable called `js` instead of the expected name (`optikon`). This is minor but it may indicate some error in the parsing of the command line parameters:

```
{:native-image {:extra-deps {clj.native-image {:git/url "https://github.com/taylorwood/clj.native-image.git"
                                               :sha     "498baa963e914fd817dbf33ea251729efd0c8f95"}}
                :main-opts  ["-m clj.native-image optikon.core"
                             "-H:Name=optikon"
                             "--language:js"]}
 :jvm-opts   ["-Dclojure.compiler.direct-linking=true"]}
```

**Comment by taylorwood** [comment]
This is apparently by design with the `native-image --language` flag: https://github.com/oracle/graal/issues/1032

If you swap the argument order it should work, or at least it did in my quick local test:
```clojure
:main-opts ["-m clj.native-image foo.core"
            "--language:js"
            "-H:Name=foo"]
```
