### ISSUE TITLE
--no-server option is frowned upon by GraalVM 19 Windows

### ISSUE THREAD

**Issue by borkdude** [taylorwood/clj.native-image#7]
The process exits with this error on Windows with GraalVM 19:

```
Error: Unrecognized option: --no-server
```

**Comment by borkdude** [comment]
This is fixed with https://github.com/taylorwood/clj.native-image/pull/9

**Comment by taylorwood** [comment]
Fixed in 546a77a4492be2f1d9b48e43cb48fb0ebfa39cc2.
